FROM 192.168.1.52/system_containers/alpine-arm64:3.10-bash

LABEL maintainer=weiwei@tenxcloud.com

ADD ./kubeadm /kubeadm

COPY run-arm64.sh /
RUN chmod 755 run-arm64.sh
VOLUME ["/tmp","/tmp"]

ENTRYPOINT ["/bin/bash", "/run-arm64.sh"]